### ISSUE TITLE
Bad value for datetime attribute in posts.html

### ISSUE THREAD

**Issue by awulkan** [reptar/reptar-theme-thread#1]
`Error: Bad value 02 November 2016 for attribute datetime on element time: The literal did not satisfy the time-datetime format.`

The W3C Validator (https://validator.w3.org/) complains about bad value in the datetime attibute shown below. 

`<time class="post-date" datetime="{{file.date | date('D MMMM YYYY')}}">{{file.date | date('D MMMM YYYY')}}</time>`

It's located in the posts.html template.

The fix is to change it to this:

`<time class="post-date" datetime="{{file.date | date('YYYY-MM-DD')}}">{{file.date | date('D MMMM YYYY')}}</time>`

I can update it if you want. :)

**Comment by awulkan** [comment]
I also noticed that the same code is present in /templates/_loop.html

**Comment by hswolff** [comment]
Awesome find! Yes please, submit a PR to update and I'll happily merge!

**Comment by hswolff** [comment]
Closed via #2
